import { Avatar, Button, Card, Form, Input, Modal, Select, Typography, Upload, message } from "antd";
import { UserOutlined, UploadOutlined, LockOutlined } from "@ant-design/icons";
import { useEffect, useState } from "react";
import { useNavigate } from "umi";
import { apiFetch, putJson, uploadFile } from "../services/api";
import { logout } from "../services/auth/authService";
import { getMyApplication, type MerchantApplication } from "../services/shop/shopService";
import type { UserView } from "../services/auth/authTypes";
const merchantStatusText: Record<string, string> = { PENDING: "申请中", APPROVED: "已入驻", REJECTED: "已驳回", CANCELLED: "已取消" };
type ProfileForm = { nickname?: string; avatarUrl?: string; gender?: string };
type PasswordForm = { oldPassword: string; newPassword: string; confirmPassword: string };
export default function ProfilePage() {
  const navigate = useNavigate(); const [user, setUser] = useState<UserView>(); const [merchantApplication, setMerchantApplication] = useState<MerchantApplication>(); const [hasMerchantApplication, setHasMerchantApplication] = useState(false); const [passwordOpen, setPasswordOpen] = useState(false); const [passwordLoading, setPasswordLoading] = useState(false);
  const [profileForm] = Form.useForm<ProfileForm>(); const [passwordForm] = Form.useForm<PasswordForm>();
  useEffect(() => { void apiFetch<UserView>("/users/me").then((value) => { setUser(value); profileForm.setFieldsValue(value); }).catch(() => undefined); void getMyApplication().then((value) => { setMerchantApplication(value); setHasMerchantApplication(true); }).catch(() => setHasMerchantApplication(false)); }, [profileForm]);
  const saveProfile = async (values: ProfileForm) => { try { const value = await putJson<UserView>("/users/me/profile", values); setUser(value); message.success("个人信息已保存"); } catch (error) { message.error(error instanceof Error ? error.message : "保存失败"); } };
  const changePassword = (values: PasswordForm) => { Modal.confirm({ title: "确认修改密码？", content: "修改成功后当前登录状态会失效，需要使用新密码重新登录。", okText: "确认修改", cancelText: "暂不修改", onOk: async () => { setPasswordLoading(true); try { await putJson("/users/me/password", values); setPasswordOpen(false); passwordForm.resetFields(); message.success("密码修改成功，请使用新密码重新登录"); try { await logout(); } catch { /* 密码已修改，前端仍需清理并回到登录页 */ } finally { navigate("/login", { replace: true }); } } catch (error) { const text = error instanceof Error ? error.message : "修改密码失败"; message.error(text.includes("原密码") ? "原始密码错误，请重新输入" : text); } finally { setPasswordLoading(false); } } }); };
  return <div className="page-content profile-page"><Card className="soft-card"><Typography.Title level={3}>个人信息</Typography.Title><Typography.Paragraph className="muted">账号：{user?.username || "加载中…"}</Typography.Paragraph><Form form={profileForm} layout="vertical" onFinish={saveProfile}><Form.Item label="头像"><Upload accept="image/png,image/jpeg,image/webp" maxCount={1} showUploadList={false} beforeUpload={(file) => { void uploadFile(file, "AVATAR").then((uploaded) => { profileForm.setFieldValue("avatarUrl", uploaded.objectKey); setUser((u) => (u ? { ...u, avatarUrl: uploaded.previewUrl } : u)); message.success("头像上传成功，请保存资料"); }).catch((error) => message.error(error instanceof Error ? error.message : "头像上传失败")); return false; }}><div style={{ cursor: "pointer" }}><Avatar size={96} src={user?.avatarUrl} icon={<UserOutlined />} /><div><UploadOutlined /> 点击上传头像</div></div></Upload></Form.Item><Form.Item name="avatarUrl" hidden><Input /></Form.Item><Form.Item name="nickname" label="昵称"><Input maxLength={64} /></Form.Item><Form.Item name="gender" label="性别"><Select allowClear options={[{ value: "UNKNOWN", label: "未知" }, { value: "MALE", label: "男" }, { value: "FEMALE", label: "女" }]} /></Form.Item><Button type="primary" htmlType="submit">保存资料</Button></Form></Card>
    <Card className="soft-card" style={{ marginTop: 16 }}><Typography.Title level={4}>商家入驻</Typography.Title>{hasMerchantApplication ? <Typography.Paragraph className="muted">{merchantApplication?.status === "APPROVED" ? "您已入驻成为平台商家，可查看商家资料。" : `当前入驻申请状态：${merchantStatusText[merchantApplication?.status || ""] || "处理中"}`}</Typography.Paragraph> : <Typography.Paragraph className="muted">您还没有入驻，点击下方按钮开始申请。</Typography.Paragraph>}<Button onClick={() => navigate("/merchant/apply")}>{hasMerchantApplication ? "查看入驻信息" : "点击入驻"}</Button></Card>
    <Card className="soft-card" style={{ marginTop: 16 }}><Typography.Title level={4}>账号安全</Typography.Title><Typography.Paragraph className="muted">如需更新登录凭据，请修改密码。修改成功后需要重新登录。</Typography.Paragraph><Button icon={<LockOutlined />} onClick={() => { passwordForm.resetFields(); setPasswordOpen(true); }}>修改密码</Button></Card>
    <Modal title="修改密码" open={passwordOpen} confirmLoading={passwordLoading} footer={null} onCancel={() => setPasswordOpen(false)} destroyOnClose><Form form={passwordForm} layout="vertical" onFinish={changePassword}><Form.Item name="oldPassword" label="原密码" rules={[{ required: true, message: "请输入原密码" }]}><Input.Password autoComplete="current-password" /></Form.Item><Form.Item name="newPassword" label="新密码" rules={[{ required: true, min: 6, max: 64, message: "请输入 6-64 位新密码" }]}><Input.Password autoComplete="new-password" /></Form.Item><Form.Item name="confirmPassword" label="确认新密码" dependencies={["newPassword"]} rules={[{ required: true, message: "请再次输入新密码" }, ({ getFieldValue }) => ({ validator(_, value) { return !value || getFieldValue("newPassword") === value ? Promise.resolve() : Promise.reject(new Error("两次输入的新密码不一致")); } })]}><Input.Password autoComplete="new-password" /></Form.Item><div style={{ textAlign: "right" }}><Button onClick={() => setPasswordOpen(false)} style={{ marginRight: 8 }}>取消</Button><Button type="primary" htmlType="submit" loading={passwordLoading}>确认修改</Button></div></Form></Modal>
  </div>;
}
