import { Button, Card, Descriptions, Empty, Input, Modal, Select, Space, Table, Tag, message } from 'antd';
import { useEffect, useState } from 'react';
import { getApplications, reviewApplication, type MerchantApplication } from '../../services/shop/shopService';
const statusText: Record<string, string> = { PENDING: '申请中', APPROVED: '已入驻', REJECTED: '已驳回', CANCELLED: '已取消' };
export default function AdminApplicationsPage() {
  const [items, setItems] = useState<MerchantApplication[]>([]);
  const [status, setStatus] = useState('PENDING');
  const load = () => void getApplications(status, 0, 100).then((p) => setItems(p.items)).catch((error) => message.error(error instanceof Error ? error.message : '申请加载失败'));
  useEffect(() => { load(); }, [status]);
  const review = (item: MerchantApplication, decision: 'APPROVED' | 'REJECTED') => { let remark = ''; Modal.confirm({ title: decision === 'APPROVED' ? '通过入驻申请？' : '驳回入驻申请？', content: <Input.TextArea placeholder="审核备注（可选）" onChange={(e) => { remark = e.target.value; }} />, okText: '确认', cancelText: '取消', onOk: async () => { try { await reviewApplication(item.id, { decision, remark }); message.success('审核结果已保存'); load(); } catch (error) { message.error(error instanceof Error ? error.message : '审核失败'); } } }); };
  const detail = (item: MerchantApplication) => Modal.info({ title: `${item.shopName} · 入驻详情`, width: 680, content: <Descriptions bordered column={1} items={[{ key: 'contact', label: '联系人', children: `${item.realName} / ${item.phone}` }, { key: 'address', label: '地址', children: `${item.province || ''}${item.city || ''}${item.district || ''}${item.addressDetail || ''}` }, { key: 'intro', label: '简介', children: item.intro || '—' }, { key: 'service', label: '服务明细', children: item.serviceItems?.length ? <Space direction="vertical">{item.serviceItems.map((service) => <div key={`${service.categoryId}-${service.title}`}><Tag color="blue">{service.categoryName || '服务分类'}</Tag> {service.title} · 起步价 ¥{service.basePrice} / {service.pricingUnit}{service.summary ? ` · ${service.summary}` : ''}</div>)}</Space> : (item.serviceNames?.length ? item.serviceNames.join('、') : '—') }, { key: 'tags', label: '商家标签', children: item.tags?.length ? item.tags.join('、') : '—' }, { key: 'radius', label: '服务覆盖半径', children: item.serviceRadiusKm ? `${item.serviceRadiusKm} 公里` : '未设置' }, { key: 'status', label: '状态', children: statusText[item.status] || item.status }, { key: 'remark', label: '审核备注', children: item.reviewRemark || '—' }, { key: 'images', label: '证明图片', children: item.images?.length ? <Space wrap>{item.images.map((img) => <img key={img.id || img.objectKey} src={img.previewUrl || `/api/files/preview?objectKey=${encodeURIComponent(img.objectKey)}`} alt={img.imageType} style={{ width: 120, height: 80, objectFit: 'cover' }} />)}</Space> : '—' }]} /> });
  return <Card><Space style={{ marginBottom: 16 }}><Select value={status} onChange={setStatus} options={[{ value: 'PENDING', label: '申请中' }, { value: 'APPROVED', label: '已通过' }, { value: 'REJECTED', label: '已驳回' }, { value: 'CANCELLED', label: '已取消' }]} /><Button onClick={load}>刷新</Button></Space><Table rowKey="id" dataSource={items} locale={{ emptyText: <Empty description="暂无入驻申请" /> }} columns={[{ title: '商铺', dataIndex: 'shopName' }, { title: '联系人', dataIndex: 'realName' }, { title: '城市', dataIndex: 'city' }, { title: '状态', dataIndex: 'status', render: (v: string) => <Tag>{statusText[v] || v}</Tag> }, { title: '操作', render: (_, item) => <><Button type="link" onClick={() => detail(item)}>查看详情</Button>{item.status === 'PENDING' && <><Button type="link" onClick={() => review(item, 'APPROVED')}>通过</Button><Button danger type="link" onClick={() => review(item, 'REJECTED')}>驳回</Button></>}</> }]} /></Card>;
}
